# Generated by Django 3.0.6 on 2020-06-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20200623_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomeUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('otp', models.IntegerField()),
                ('otp_exp', models.DateTimeField(auto_now=True)),
                ('role', models.IntegerField()),
                ('profile_img', models.CharField(max_length=255)),
                ('notification', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
