# Generated by Django 3.0.6 on 2020-06-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20200623_1924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomeUsers',
            new_name='Coders',
        ),
    ]
